Share configuration across classes
open-meteo-ruby/open-meteo-ruby pull request #64
Opened 2024-03-08 12:53 UTC by martinezcoder

2024-03-08 14:52 UTC, peterfication requested changes
The README needs an update as well. And while you're at it, you can add the docs about the timeouts as well.

2024-03-14 06:20 UTC, peterfication approved these changes

2024-03-14 06:20 UTC, peterfication commented on lib/open_meteo/faraday_connection.rb
> +        conn.response :logger
I'd say yes 👍 Do we need to pass the logger from the config?

2024-03-14 14:58 UTC, martinezcoder commented on lib/open_meteo/faraday_connection.rb
> +        conn.response :logger
It is not necessary, if it's always here as a constant, the api call is logged in the output of the console, so I think it helps.

2024-03-18 08:53 UTC, peterfication approved these changes

2024-03-21 15:16 UTC, merged